'use client'

import { useState } from 'react'
import type { ReactNode } from 'react'
import {
  Activity, AlertTriangle, ArrowLeft, Bell, CheckCircle2, ChevronLeft, ChevronRight,
  Download, FileBarChart, FileImage, FileText, Filter, FolderSearch, Gauge, Grid2X2,
  LayoutDashboard, List, Menu, Pause, Play, Plus, Search, Settings, ShieldCheck,
  SlidersHorizontal, Upload, UserRound, Video, Volume2, X, ZoomIn,
} from 'lucide-react'

type View = 'Overview' | 'Investigations' | 'Investigation Detail' | 'Video Evidence' | 'Timeline' | 'Detections' | 'Entities' | 'Entity Detail' | 'Events' | 'Evidence' | 'Comparison' | 'Integrity' | 'Reports' | 'Processing'

export interface Investigation { id: string; title: string; camera?: string; source?: string; duration?: string; entities?: number; events?: number; integrity?: string; status?: string; updated?: string }
export interface Video { id: string; filename: string; source?: string; duration?: string; metadata?: Record<string, string>; status?: string }
export interface Camera { id: string; name?: string; location?: string }
export interface Detection { time: string; object: string; entity: string; track: string; confidence: number; source: string; frame: string; status: string }
export interface Entity { id: string; type: string; first?: string; last?: string; observations?: number; confidence?: number; track?: string; status?: string }
export interface EntityObservation { time: string; type: string; description?: string }
export interface ForensicEvent { type: string; time?: string; entities?: string; confidence?: number; evidence?: number; status?: string }
export interface Evidence { frame: string; time?: string; label: string; entity?: string; event?: string; type: string; src?: string }
export interface IntegrityResult { status: 'unknown' | 'verified' | 'review' | 'failed'; score?: number; checks?: string[]; metadata?: Record<string, string> }
export interface ForensicReport { id: string; investigationId: string; status: string; createdAt?: string; events?: number; entities?: number; integrity?: IntegrityResult }
export interface ProcessingStatus { status: 'idle' | 'queued' | 'processing' | 'complete' | 'failed'; step?: string; progress?: number; message?: string }

const nav: [string, React.ComponentType<{ size?: number }>|typeof ScanIcon][] = [
  ['Overview', LayoutDashboard], ['Investigations', FolderSearch], ['Video Evidence', Video], ['Timeline', Activity], ['Detections', ScanIcon], ['Entities', UserRound], ['Events', Activity], ['Evidence', FileImage], ['Integrity', ShieldCheck], ['Reports', FileBarChart],
]
function ScanIcon({ size = 18 }: { size?: number }) { return <span className="scan-icon" style={{ width: size, height: size }} /> }
function Button({ children, onClick, variant = 'secondary', icon: Icon, className = '' }: { children?: ReactNode; onClick?: () => void; variant?: string; icon?: React.ComponentType<{ size?: number }>; className?: string }) { return <button onClick={onClick} className={`btn btn-${variant} ${className}`}>{Icon && <Icon size={15} />}{children}</button> }
function EmptyState({ title, description, action, onAction, icon: Icon = FolderSearch }: { title: string; description: string; action?: string; onAction?: () => void; icon?: React.ComponentType<{ size?: number }> }) { return <div className="empty-state"><div className="empty-icon"><Icon size={22} /></div><h3>{title}</h3><p>{description}</p>{action && <Button variant="primary" onClick={onAction} icon={Plus}>{action}</Button>}</div> }
function StatusBadge({ children, tone = 'slate' }: { children: ReactNode; tone?: string }) { return <span className={`status status-${tone}`}>{children}</span> }
function Filters({ search, setSearch, children }: { search: string; setSearch: (value: string) => void; children?: ReactNode }) { return <div className="filters"><div className="filter-search"><Search size={15} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search records..." /></div><Button icon={Filter}>Filters</Button>{children || <Button>Status <ChevronRight size={14} /></Button>}<Button icon={SlidersHorizontal}>Customize</Button></div> }
function Sidebar({ view, setView, open, setOpen }: { view: View; setView: (view: View) => void; open: boolean; setOpen: (open: boolean) => void }) { return <><div className={`sidebar-backdrop ${open ? 'visible' : ''}`} onClick={() => setOpen(false)} /><aside className={`sidebar ${open ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><span /><span /><span /></div><div><strong>TRACE-X</strong><small>FORENSIC WORKSTATION</small></div><button className="collapse" onClick={() => setOpen(false)} aria-label="Close navigation"><ChevronLeft size={17} /></button></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(([label, Icon]) => <button key={label} onClick={() => { setView(label as View); setOpen(false) }} className={view === label ? 'active' : ''}><Icon size={17} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="system"><span className="pulse" /><div><b>Analysis Engine</b><small>Ready for connection</small></div></div><button onClick={() => { setView('Processing'); setOpen(false) }}><Gauge size={17} /><span>Processing</span></button><button><Settings size={17} /><span>Settings</span></button></div></aside></> }
function Header({ view, setOpen }: { view: View; setOpen: (open: boolean) => void }) { return <header className="topbar"><button className="mobile-menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={18} /></button><div className="crumb"><span>Trace-X</span><ChevronRight size={14} /><b>{view}</b></div><div className="header-actions"><div className="global-search"><Search size={16} /><input aria-label="Global search" placeholder="Search workspace..." /><kbd>⌘ K</kbd></div><button className="icon-btn" aria-label="Notifications"><Bell size={17} /></button><button className="icon-btn" aria-label="Settings"><Settings size={17} /></button></div></header> }
function PageTitle({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Overview({ setView }: { setView: (view: View) => void }) { const cards = [['Investigations','No data available',FolderSearch],['Evidence','Awaiting analysis',FileImage],['Detections','No data available',ScanIcon],['Entities','No data available',UserRound],['Events','Awaiting analysis',Activity],['Integrity','Not analyzed',ShieldCheck]] as const; return <div className="page"><PageTitle eyebrow="OPERATIONS / OVERVIEW" title="Investigation Overview" description="Connect your existing Trace-X backend to populate this workspace." action={<Button variant="primary" icon={Plus} onClick={() => setView('Investigations')}>New investigation</Button>} /><div className="overview-cards">{cards.map(([label, value, Icon]) => <div className="metric" key={label}><div className="metric-icon navy"><Icon size={17} /></div><div><p>{label}</p><strong>—</strong><small>{value}</small></div></div>)}</div><div className="panel overview-empty"><EmptyState title="No workspace activity yet" description="Investigation, evidence, detection and integrity data will appear here when supplied by your backend." action="Open investigations" onAction={() => setView('Investigations')} icon={Activity} /></div></div> }
function Investigations({ setView }: { setView: (view: View) => void }) { const [search, setSearch] = useState(''); return <div className="page"><PageTitle eyebrow="CASE MANAGEMENT" title="Investigations" description="Browse and manage video forensic investigations." action={<Button variant="primary" icon={Plus}>New investigation</Button>} /><Filters search={search} setSearch={setSearch} /><div className="panel"><EmptyState title="No investigations yet" description="Investigation records supplied by your backend will appear here." action="New investigation" icon={FolderSearch} /></div></div> }
function VideoViewer() { const [playing, setPlaying] = useState(false); const [filter, setFilter] = useState('Standard'); const [speed, setSpeed] = useState('1x'); const [overlays, setOverlays] = useState({ detections: false, tracks: false, confidence: false, motion: false, evidence: false }); const classes = filter === 'Night Vision' ? 'night' : filter === 'Invert' ? 'invert' : filter === 'High Contrast' ? 'contrast' : filter === 'Sharpen Detail' ? 'sharpen' : ''; return <div className="viewer-wrap"><div className="viewer-controls"><div><p className="eyebrow">SURVEILLANCE FILTER</p><div className="segmented">{['Standard','Night Vision','Invert','High Contrast','Sharpen Detail'].map(item => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></div><div><p className="eyebrow">PLAYBACK SPEED</p><div className="segmented">{['0.25x','0.5x','1x','1.5x','2x'].map(item => <button className={speed === item ? 'active' : ''} onClick={() => setSpeed(item)} key={item}>{item}</button>)}</div></div></div><div className="viewer"><div className={`cctv-scene ${classes}`}><div className="scene-placeholder"><Video size={30} /><b>No video loaded</b><span>Connect a video source to begin analysis</span></div>{overlays.detections && <div className="overlay-placeholder">Detection overlays will render from backend data</div>}</div><div className="viewer-toolbar"><button className="transport primary-transport" onClick={() => setPlaying(!playing)}>{playing ? <Pause size={15} /> : <Play size={15} />}</button><button className="transport" aria-label="Previous frame"><ArrowLeft size={15} /></button><button className="transport" aria-label="Next frame"><ChevronRight size={15} /></button><Volume2 size={15} /><div className="scrub" /><span className="toolbar-readout">— <small>FRAME —</small></span></div></div><div className="overlay-toggles">{Object.entries({ detections: 'Show detections', tracks: 'Show track IDs', confidence: 'Show confidence', motion: 'Show motion', evidence: 'Show evidence markers' }).map(([key, label]) => <button key={key} className={`toggle-row ${overlays[key as keyof typeof overlays] ? 'checked' : ''}`} onClick={() => setOverlays(old => ({ ...old, [key]: !old[key as keyof typeof overlays] }))}><span>{label}</span><i><b /></i></button>)}</div></div> }
function Timeline({ full = false }: { full?: boolean }) { return <div className={`timeline-card panel ${full ? 'timeline-full' : ''}`}><div className="section-head"><div><p className="eyebrow">SYNCHRONIZED ANALYSIS</p><h3>Forensic timeline</h3></div><Button icon={ZoomIn}>Zoom</Button></div><div className="timeline-empty"><Activity size={20} /><span>Load video evidence to begin timeline analysis.</span></div></div> }
function InvestigationDetail({ setView }: { setView: (view: View) => void }) { return <div className="page detail-page"><PageTitle eyebrow="INVESTIGATION WORKSPACE" title="Investigation workspace" description="Load an investigation from your backend to begin review." action={<Button variant="primary" icon={Upload}>Load video</Button>} /><div className="workspace-grid"><div><VideoViewer /><Timeline /></div><div className="panel right-panel"><div className="section-head"><div><p className="eyebrow">FORENSIC PANEL</p><h3>Review context</h3></div><button className="icon-btn"><X size={16} /></button></div><EmptyState title="No event selected" description="Detections, entities, events and evidence will be linked here when available." icon={Activity} /><Button variant="secondary" className="full" onClick={() => setView('Evidence')}>Open evidence</Button></div></div></div> }
function EmptyExplorer({ type, description, icon: Icon = FolderSearch }: { type: string; description: string; icon?: React.ComponentType<{ size?: number }> }) { return <div className="page"><PageTitle eyebrow={`ANALYSIS / ${type.toUpperCase()}`} title={type} description={description} /><Filters search="" setSearch={() => {}} /><div className="panel"><EmptyState title={`No ${type.toLowerCase()} available`} description={`No ${type.toLowerCase()} records have been supplied yet.`} icon={Icon} /></div></div> }
function Processing() { const steps = ['Video ingestion','Frame extraction','Motion analysis','Object detection','Object verification','Entity tracking','Event reconstruction','Integrity analysis','Evidence generation']; return <div className="page"><PageTitle eyebrow="PIPELINE / ANALYSIS" title="Processing" description="Track analysis stages supplied by your backend." /><div className="panel pipeline-panel"><EmptyState title="No processing job" description="Processing stages and status will appear here when a video analysis job is connected." icon={Gauge} /><div className="pipeline-empty-list">{steps.map(step => <div className="pipeline-step" key={step}><span /><b>{step}</b><StatusBadge>Waiting</StatusBadge></div>)}</div></div></div> }
function Integrity() { return <div className="page"><PageTitle eyebrow="VALIDATION / SOURCE" title="Evidence Integrity" description="Technical verification results for connected video evidence." /><div className="panel"><EmptyState title="No integrity analysis available" description="Container, codec, hash, timestamp and manipulation checks will appear after analysis." icon={ShieldCheck} /></div></div> }
function Reports() { return <div className="page"><PageTitle eyebrow="DOCUMENTS / OUTPUT" title="Reports" description="Review and export structured forensic reports." action={<Button variant="primary" icon={FileText}>Generate report</Button>} /><div className="panel"><EmptyState title="No reports available" description="Generated reports supplied by your backend will appear here." icon={FileBarChart} /></div></div> }
function Drawer({ title, onClose }: { title: string; onClose: () => void }) { return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={e => e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">TRACE-X DETAIL</p><h3>{title}</h3></div><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={17} /></button></div><EmptyState title="No data available" description="This panel is ready for backend-provided details." /></aside></div> }

export default function Page() { const [view, setView] = useState<View>('Overview'); const [open, setOpen] = useState(true); let content: ReactNode; switch (view) { case 'Overview': content = <Overview setView={setView} />; break; case 'Investigations': content = <Investigations setView={setView} />; break; case 'Investigation Detail': content = <InvestigationDetail setView={setView} />; break; case 'Video Evidence': content = <EmptyExplorer type="Video Evidence" description="Uploaded and processed video sources from your workspace." icon={Video} />; break; case 'Timeline': content = <><div className="page"><PageTitle eyebrow="ANALYSIS / TIME" title="Forensic timeline" description="Cross-channel view of frames, motion, entities, events and evidence." /><Timeline full /></div></>; break; case 'Detections': content = <EmptyExplorer type="Detections" description="Review model observations across frames, tracks and sources." icon={ScanIcon} />; break; case 'Entities': content = <EmptyExplorer type="Entities" description="Individual physical objects tracked across investigations." icon={UserRound} />; break; case 'Entity Detail': content = <EmptyExplorer type="Entity detail" description="Select an entity from the explorer to inspect its history." icon={UserRound} />; break; case 'Events': content = <EmptyExplorer type="Events" description="Reconstructed activity and event relationships from analyzed video." icon={Activity} />; break; case 'Evidence': content = <EmptyExplorer type="Evidence" description="Evidence frames linked to detections, entities and events." icon={FileImage} />; break; case 'Comparison': content = <EmptyExplorer type="Evidence comparison" description="Compare backend-provided frames without unsupported conclusions." icon={FileImage} />; break; case 'Integrity': content = <Integrity />; break; case 'Reports': content = <Reports />; break; case 'Processing': content = <Processing />; break; default: content = <Overview setView={setView} /> } return <div className="app-shell"><Sidebar view={view} setView={setView} open={open} setOpen={setOpen} /><div className="app-main"><Header view={view} setOpen={setOpen} /><main>{content}</main></div></div> }
